In [1]:
import pandas as pd
import random
from datetime import datetime, timedelta

random.seed(42)

In [2]:
cd F:Downloads

F:\Downloads

In [4]:
companies_df = pd.read_csv(
    "projectflow-analytics/data/raw/companies.csv"
)

companies_df.head()

,company_id,company_code,company_name,industry,city,state,employee_count,registration_date,company_status
0,1,CMP001,Nexora Technologies,SaaS,Chennai,Tamil Nadu,224,2024-07-17,Active
1,2,CMP002,CloudMint Labs,AI,Bengaluru,Karnataka,859,2023-06-28,Active
2,3,CMP003,BrightStack Systems,SaaS,Ahmedabad,Gujarat,787,2024-03-23,Active
3,4,CMP004,CodeSphere Tech,SaaS,Hyderabad,Telangana,4617,2024-02-12,Active
4,5,CMP005,DataSprint Solutions,HRTech,Chennai,Tamil Nadu,3456,2024-03-27,Active

In [5]:
first_names = [
    "Aarav",
    "Vivaan",
    "Aditya",
    "Rahul",
    "Samir",
    "Priya",
    "Sneha",
    "Ananya",
    "Kavya",
    "Neha"
]


last_names = [
    "Sharma",
    "Patel",
    "Singh",
    "Mehta",
    "Verma",
    "Shah"
]


roles = [
    "Owner",
    "Project Manager",
    "Developer",
    "Designer",
    "QA"
]

In [6]:
users = []

user_id = 1


for company in companies_df.itertuples():

    total_users = random.randint(20, 60)


    for i in range(total_users):

        first = random.choice(first_names)

        last = random.choice(last_names)


        users.append({

            "user_id": user_id,

            "user_code": f"USR{user_id:04}",

            "company_id": company.company_id,

            "full_name": first + " " + last,

            "email": f"{first.lower()}.{last.lower()}{user_id}@projectflow.com",

            "role": random.choices(
                roles,
                weights=[3,10,60,15,12]
            )[0],

            "join_date": (
                pd.to_datetime(company.registration_date)
                +
                timedelta(days=random.randint(1,300))
            ).date(),

            "last_login": datetime(
                2026,
                random.randint(1,7),
                random.randint(1,28),
                random.randint(0,23),
                random.randint(0,59)
            ),

            "user_status": random.choices(
                ["Active","Inactive"],
                weights=[95,5]
            )[0]

        })


        user_id += 1

In [7]:
users_df = pd.DataFrame(users)

users_df.head()

,user_id,user_code,company_id,full_name,email,role,join_date,last_login,user_status
0,1,USR0001,1,Vivaan Sharma,vivaan.sharma1@projectflow.com,Designer,2024-11-20,2026-02-05 23:06:00,Active
1,2,USR0002,1,Kavya Sharma,kavya.sharma2@projectflow.com,Developer,2024-08-03,2026-01-03 06:14:00,Active
2,3,USR0003,1,Aarav Verma,aarav.verma3@projectflow.com,Developer,2025-04-23,2026-04-08 14:37:00,Active
3,4,USR0004,1,Aarav Patel,aarav.patel4@projectflow.com,Developer,2025-01-08,2026-03-05 06:48:00,Active
4,5,USR0005,1,Vivaan Mehta,vivaan.mehta5@projectflow.com,Project Manager,2025-01-10,2026-05-09 01:46:00,Active

In [8]:
users_df.to_csv(
    "projectflow-analytics/data/raw/users.csv",
    index=False
)