In [1]:
import pandas as pd
import random
from datetime import timedelta

random.seed(42)

In [2]:
cd F:Downloads

F:\Downloads

In [3]:
companies_df = pd.read_csv(
    "projectflow-analytics/data/raw/companies.csv"
)

users_df = pd.read_csv(
    "projectflow-analytics/data/raw/users.csv"
)


companies_df.head()

,company_id,company_code,company_name,industry,city,state,employee_count,registration_date,company_status
0,1,CMP001,Nexora Technologies,SaaS,Chennai,Tamil Nadu,224,2024-07-17,Active
1,2,CMP002,CloudMint Labs,AI,Bengaluru,Karnataka,859,2023-06-28,Active
2,3,CMP003,BrightStack Systems,SaaS,Ahmedabad,Gujarat,787,2024-03-23,Active
3,4,CMP004,CodeSphere Tech,SaaS,Hyderabad,Telangana,4617,2024-02-12,Active
4,5,CMP005,DataSprint Solutions,HRTech,Chennai,Tamil Nadu,3456,2024-03-27,Active

In [4]:
project_names = [
    "Customer Analytics Platform",
    "AI Chat Assistant",
    "Mobile App Redesign",
    "Payment Integration System",
    "HR Management Portal",
    "Marketing Automation Tool",
    "Sales Dashboard",
    "Cloud Migration Project",
    "Security Monitoring System",
    "Data Warehouse Setup"
]


project_status = [
    "Planning",
    "Active",
    "Completed",
    "On Hold",
    "Cancelled"
]


priority = [
    "Low",
    "Medium",
    "High",
    "Critical"
]

In [5]:
projects = []

project_id = 1


for company in companies_df.itertuples():


    company_users = users_df[
        users_df["company_id"] == company.company_id
    ]


    total_projects = random.randint(5, 15)


    for i in range(total_projects):


        start_date = (
            pd.to_datetime(company.registration_date)
            +
            timedelta(days=random.randint(30,500))
        )


        projects.append({

            "project_id": project_id,


            "project_code": f"PRJ{project_id:04}",


            "company_id": company.company_id,


            "created_by": random.choice(
                company_users["user_id"].tolist()
            ),


            "project_name": random.choice(project_names),


            "project_status": random.choices(
                project_status,
                weights=[10,45,35,8,2]
            )[0],


            "priority": random.choices(
                priority,
                weights=[20,50,25,5]
            )[0],


            "start_date": start_date.date(),


            "due_date": (
                start_date
                +
                timedelta(days=random.randint(30,365))
            ).date()

        })


        project_id += 1

In [6]:
projects_df = pd.DataFrame(projects)
projects_df.head()

,project_id,project_code,company_id,created_by,project_name,project_status,priority,start_date,due_date
0,1,PRJ0001,1,2,HR Management Portal,Active,Low,2024-10-12,2025-01-02
1,2,PRJ0002,1,48,Security Monitoring System,Planning,Medium,2025-07-28,2025-09-11
2,3,PRJ0003,1,14,Payment Integration System,Active,Low,2024-10-02,2025-02-10
3,4,PRJ0004,1,42,Security Monitoring System,Active,Medium,2025-08-17,2026-02-05
4,5,PRJ0005,1,56,Customer Analytics Platform,Completed,Low,2025-10-04,2026-06-07

In [7]:
projects_df.to_csv(
    "projectflow-analytics/data/raw/projects.csv",
    index=False
)