In [1]:
import pandas as pd
import random
from datetime import timedelta

random.seed(42)

In [2]:
cd F:Downloads

F:\Downloads

In [3]:
projects_df = pd.read_csv(
    "projectflow-analytics/data/raw/projects.csv"
)

users_df = pd.read_csv(
    "projectflow-analytics/data/raw/users.csv"
)


projects_df.head()

,project_id,project_code,company_id,created_by,project_name,project_status,priority,start_date,due_date
0,1,PRJ0001,1,2,HR Management Portal,Active,Low,2024-10-12,2025-01-02
1,2,PRJ0002,1,48,Security Monitoring System,Planning,Medium,2025-07-28,2025-09-11
2,3,PRJ0003,1,14,Payment Integration System,Active,Low,2024-10-02,2025-02-10
3,4,PRJ0004,1,42,Security Monitoring System,Active,Medium,2025-08-17,2026-02-05
4,5,PRJ0005,1,56,Customer Analytics Platform,Completed,Low,2025-10-04,2026-06-07

In [4]:
task_names = [
    "Design User Interface",
    "Create Database Schema",
    "Develop API",
    "Testing Module",
    "Fix Bugs",
    "Create Dashboard",
    "Write Documentation",
    "Optimize Performance",
    "Deploy Application",
    "Security Testing"
]


task_status = [
    "pending",
    "in progress",
    "completed"
]


priority = [
    "low",
    "medium",
    "high",
    "critical"
]

In [5]:
tasks = []

task_id = 1


for project in projects_df.itertuples():


    company_users = users_df[
        users_df["company_id"] == project.company_id
    ]


    total_tasks = random.randint(10,40)


    for i in range(total_tasks):


        created_date = (
            pd.to_datetime(project.start_date)
            +
            timedelta(days=random.randint(1,30))
        )


        status = random.choices(
            task_status,
            weights=[25,35,40]
        )[0]


        completed_date = None


        if status == "completed":

            completed_date = (
                created_date
                +
                timedelta(days=random.randint(1,20))
            ).date()


        tasks.append({

            "task_id": task_id,

            "task_code": f"TSK{task_id:05}",

            "project_id": project.project_id,

            "assigned_user_id": random.choice(
                company_users["user_id"].tolist()
            ),

            "task_name": random.choice(task_names),

            "task_status": status,

            "priority": random.choices(
                priority,
                weights=[20,50,25,5]
            )[0],

            "created_date": created_date.date(),

            "due_date": (
                created_date
                +
                timedelta(days=random.randint(7,60))
            ).date(),

            "completed_date": completed_date

        })


        task_id += 1

In [6]:
tasks_df = pd.DataFrame(tasks)
tasks_df.head()

,task_id,task_code,project_id,assigned_user_id,task_name,task_status,priority,created_date,due_date,completed_date
0,1,TSK00001,1,18,Testing Module,pending,medium,2024-10-16,2024-12-09,None
1,2,TSK00002,1,6,Security Testing,completed,medium,2024-10-16,2024-10-24,2024-11-03
2,3,TSK00003,1,33,Security Testing,pending,low,2024-10-15,2024-11-03,None
3,4,TSK00004,1,27,Testing Module,completed,medium,2024-11-04,2024-11-28,2024-11-22
4,5,TSK00005,1,45,Write Documentation,completed,medium,2024-11-07,2024-11-23,2024-11-13

In [7]:
tasks_df.to_csv(
    "projectflow-analytics/data/raw/tasks.csv",
    index=False
)