In [1]:
import pandas as pd
import random
from datetime import timedelta

random.seed(42)

In [2]:
cd F:Downloads

F:\Downloads

In [3]:
tasks_df = pd.read_csv(
    "projectflow-analytics/data/raw/tasks.csv"
)

users_df = pd.read_csv(
    "projectflow-analytics/data/raw/users.csv"
)


tasks_df.head()

,task_id,task_code,project_id,assigned_user_id,task_name,task_status,priority,created_date,due_date,completed_date
0,1,TSK00001,1,18,Testing Module,pending,medium,2024-10-16,2024-12-09,NaN
1,2,TSK00002,1,6,Security Testing,completed,medium,2024-10-16,2024-10-24,2024-11-03
2,3,TSK00003,1,33,Security Testing,pending,low,2024-10-15,2024-11-03,NaN
3,4,TSK00004,1,27,Testing Module,completed,medium,2024-11-04,2024-11-28,2024-11-22
4,5,TSK00005,1,45,Write Documentation,completed,medium,2024-11-07,2024-11-23,2024-11-13

In [4]:
comment_messages = [
    "Task completed successfully",
    "Need some improvements",
    "Working on this task",
    "Bug fixed",
    "Code review completed",
    "Testing is in progress",
    "Changes requested",
    "Approved",
    "Waiting for confirmation",
    "Documentation updated"
]

In [5]:
comments = []

comment_id = 1


for task in tasks_df.itertuples():


    total_comments = random.randint(0,5)


    for i in range(total_comments):


        comments.append({

            "comment_id": comment_id,


            "task_id": task.task_id,


            "user_id": task.assigned_user_id,


            "comment_text": random.choice(
                comment_messages
            ),


            "commented_at": (
                pd.to_datetime(task.created_date)
                +
                timedelta(
                    days=random.randint(0,20),
                    hours=random.randint(1,23)
                )
            )

        })


        comment_id += 1

In [6]:
comments_df = pd.DataFrame(comments)
comments_df.head()

,comment_id,task_id,user_id,comment_text,commented_at
0,1,1,18,Need some improvements,2024-10-16 09:00:00
1,2,1,18,Bug fixed,2024-10-23 05:00:00
2,3,1,18,Need some improvements,2024-11-02 03:00:00
3,4,1,18,Documentation updated,2024-10-29 02:00:00
4,5,1,18,Task completed successfully,2024-10-18 07:00:00

In [8]:
comments_df.to_csv(
    "projectflow-analytics/data/raw/comments.csv",
    index=False
)