In [1]:
cd F:Downloads

F:\Downloads

In [2]:
import pandas as pd
import random
from datetime import timedelta

random.seed(42)

In [3]:
companies_df = pd.read_csv(
    "projectflow-analytics/data/raw/companies.csv"
)

companies_df.head()

,company_id,company_code,company_name,industry,city,state,employee_count,registration_date,company_status
0,1,CMP001,Nexora Technologies,SaaS,Chennai,Tamil Nadu,224,2024-07-17,Active
1,2,CMP002,CloudMint Labs,AI,Bengaluru,Karnataka,859,2023-06-28,Active
2,3,CMP003,BrightStack Systems,SaaS,Ahmedabad,Gujarat,787,2024-03-23,Active
3,4,CMP004,CodeSphere Tech,SaaS,Hyderabad,Telangana,4617,2024-02-12,Active
4,5,CMP005,DataSprint Solutions,HRTech,Chennai,Tamil Nadu,3456,2024-03-27,Active

In [4]:
plans = {
    "free": 0,
    "starter": 999,
    "pro": 4999,
    "enterprise": 19999
}


status = [
    "active",
    "expired",
    "cancelled"
]

In [5]:
subscriptions = []

subscription_id = 1


for company in companies_df.itertuples():


    first_plan = random.choice(
        ["free", "starter", "pro"]
    )


    start_date = pd.to_datetime(
        company.registration_date
    )


    subscriptions.append({

        "subscription_id": subscription_id,

        "company_id": company.company_id,

        "plan_name": first_plan,

        "monthly_price": plans[first_plan],

        "start_date": start_date.date(),

        "end_date": None,

        "subscription_status": "active"

    })


    subscription_id += 1



    # some companies upgrade later

    if random.random() < 0.35:


        upgrade_plan = random.choice(
            ["pro", "enterprise"]
        )


        upgrade_date = (
            start_date
            +
            timedelta(
                days=random.randint(90,400)
            )
        )


        subscriptions[-1]["end_date"] = upgrade_date.date()

        subscriptions[-1]["subscription_status"] = "expired"


        subscriptions.append({

            "subscription_id": subscription_id,

            "company_id": company.company_id,

            "plan_name": upgrade_plan,

            "monthly_price": plans[upgrade_plan],

            "start_date": upgrade_date.date(),

            "end_date": None,

            "subscription_status": "active"

        })


        subscription_id += 1

In [6]:
subscription_df = pd.DataFrame(
    subscriptions
)

subscription_df.head()

,subscription_id,company_id,plan_name,monthly_price,start_date,end_date,subscription_status
0,1,1,pro,4999,2024-07-17,2025-02-17,expired
1,2,1,enterprise,19999,2025-02-17,None,active
2,3,2,free,0,2023-06-28,2024-07-01,expired
3,4,2,pro,4999,2024-07-01,None,active
4,5,3,free,0,2024-03-23,None,active

In [7]:
subscription_df.to_csv(
    "projectflow-analytics/data/raw/subscription_history.csv",
    index=False
)