In [1]:
cd F:Downloads

F:\Downloads

In [2]:
import pandas as pd
import random
from datetime import datetime, timedelta

random.seed(42)

In [3]:
users_df = pd.read_csv(
    "projectflow-analytics/data/raw/users.csv"
)


users_df.head()

,user_id,user_code,company_id,full_name,email,role,join_date,last_login,user_status
0,1,USR0001,1,Vivaan Sharma,vivaan.sharma1@projectflow.com,Designer,2024-11-20,2026-02-05 23:06:00,Active
1,2,USR0002,1,Kavya Sharma,kavya.sharma2@projectflow.com,Developer,2024-08-03,2026-01-03 06:14:00,Active
2,3,USR0003,1,Aarav Verma,aarav.verma3@projectflow.com,Developer,2025-04-23,2026-04-08 14:37:00,Active
3,4,USR0004,1,Aarav Patel,aarav.patel4@projectflow.com,Developer,2025-01-08,2026-03-05 06:48:00,Active
4,5,USR0005,1,Vivaan Mehta,vivaan.mehta5@projectflow.com,Project Manager,2025-01-10,2026-05-09 01:46:00,Active

In [4]:
activity_types = [
    "login",
    "logout",
    "project_created",
    "task_created",
    "task_completed",
    "comment_added",
    "ai_used"
]

In [5]:
activity_logs = []

activity_id = 1


for user in users_df.itertuples():


    # active users have more activity

    if user.user_status == "Active":

        total_activity = random.randint(50,200)

    else:

        total_activity = random.randint(5,30)



    for i in range(total_activity):


        activity_logs.append({

            "activity_id": activity_id,


            "user_id": user.user_id,


            "activity_type": random.choices(

                activity_types,

                weights=[
                    35,   # login
                    20,   # logout
                    5,    # project create
                    15,   # task create
                    15,   # task complete
                    8,    # comments
                    2     # AI
                ]

            )[0],


            "activity_time": (

                datetime(2026,1,1)

                +

                timedelta(

                    days=random.randint(0,180),

                    hours=random.randint(0,23),

                    minutes=random.randint(0,59)

                )

            )

        })


        activity_id += 1

In [6]:
activity_logs_df = pd.DataFrame(
    activity_logs
)


activity_logs_df.head()

   activity_id  user_id   activity_type       activity_time
0            1        1           login 2026-03-12 07:14:00
1            2        1           login 2026-01-27 21:47:00
2            3        1  task_completed 2026-01-23 18:27:00
3            4        1           login 2026-01-24 06:14:00
4            5        1          logout 2026-01-07 17:12:00

In [7]:
activity_logs_df.to_csv(
    "projectflow-analytics/data/raw/activity_logs.csv",
    index=False
)